# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL # Uncomment to disable checks of spelling mistakes
  - REPOSITORY

DISABLE_LINTERS:
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - BASH_EXEC

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

COPYPASTE_FILTER_REGEX_EXCLUDE: .*/migrations/
PYTHON_BANDIT_FILTER_REGEX_EXCLUDE: tests
PYTHON_MYPY_FILTER_REGEX_EXCLUDE: tests|manage\.py

# see https://github.com/oxsecurity/megalinter/issues/1975#issuecomment-1283162672
PRE_COMMANDS:
  - command: |-
      echo $(ls -lah .gitignore | sed 's/\s\+/ /g' | cut -d ' ' -f3,4 | sed 's/ /\:/') > perms.txt
    cwd: "workspace"

POST_COMMANDS:
  - command: |-
      find . -user root -group root -exec chown $(cat perms.txt) {} \;
      rm perms.txt
    cwd: "workspace"
