"""
Base classes for Blog app views.
"""

from django.utils.decorators import method_decorator
from drf_yasg.utils import swagger_auto_schema
from rest_framework.viewsets import ModelViewSet


@method_decorator(
    name="list", decorator=swagger_auto_schema(responses={404: "Not found"})
)
@method_decorator(
    name="create", decorator=swagger_auto_schema(responses={400: "Bad request"})
)
@method_decorator(
    name="retrieve", decorator=swagger_auto_schema(responses={404: "Not found"})
)
@method_decorator(
    name="update", decorator=swagger_auto_schema(responses={404: "Not found"})
)
@method_decorator(
    name="partial_update", decorator=swagger_auto_schema(responses={404: "Not found"})
)
@method_decorator(
    name="destroy", decorator=swagger_auto_schema(responses={404: "Not found"})
)
class BaseViewSet(ModelViewSet):
    """
    Base view set class for the API.

    Provides workarounds for non-compliance of
    API schema generated by drf_yasg with OpenAPI specs.
    """
