# Generated by Django 5.0.2 on 2024-02-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.PositiveBigIntegerField(
                        default=99999942,
                        help_text="Original poster ID",
                        verbose_name="User ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short summary of this blog post", max_length=255
                    ),
                ),
                ("body", models.TextField(help_text="Full content of this blog post")),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Commenter's name", max_length=255),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Commenter's email address", max_length=254
                    ),
                ),
                ("body", models.TextField(help_text="Full content of this comment")),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The blog post for which the comment was made.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
