# Generated by Django 5.0.2 on 2024-02-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("success", models.BooleanField(blank=True, null=True)),
                ("record_count", models.PositiveBigIntegerField(default=0)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
